add structs representing parts of the parsed certificate
misoxxx/sparse pull request #13
Opened 2021-03-20 21:36 UTC by mdugacek

This PR adds stracts that represent parts of the parsed certificate.
Parts of the certificate are: `title`, `versions`, `table_of_content`, `revisions`, `bibliography` and `other`.

All structures contains also `using` for type of the data they hold:
```c++
// You do not have to write
std::vector<std::unordered_map<std::string, std::string>> fun();

// You can just use
versions::data_t fun();
```

Closes #5

2021-03-20 22:39 UTC, ondrys123 requested changes

2021-03-20 22:39 UTC, ondrys123 commented on include/sparse/common/types.hpp
> +    using data_t = std::unordered_map<std::string, std::vector<std::string>>;
I am not sure whether unordered map is the correct approach because we will have at most 7 keys, which are in fixed order (`eal, global_platform, java_card, sha, rsa, ecc, des`). But if you use undordered map like this, it's not obvious what the map can hold (anything can be a key, but only 7 keys are valid)

I think it would be better to define a nested struct with 7 members, the content of `versions` becomes more explicit.

2021-03-20 22:39 UTC, ondrys123 commented on include/sparse/common/types.hpp
> +    using data_t = std::vector<std::tuple<std::string, std::string, int>>;
I think it would be better to use fixed-size integer type, such as `uint32_t`, we can safely assume that negative page numbers are not valid, so there's no need for signed type.

Also, when you look at `std::tuple<std::string, std::string, int>`, it's hard to tell what is what without looking at the readme or some parsed data. I think it would be better to define struct which have members with corresponding names. We can discuss this, but at the very least, it should be written in the documentation that the order is "section number", "name", "page". 
If we ever need tuple-like behaviour, we can specialise `std::get`

2021-03-20 22:39 UTC, ondrys123 commented on include/sparse/common/types.hpp
> +    using data_t = std::vector<std::unordered_map<std::string, std::string>>;
The revision is supposed to be list of objects like this:
```
{
    "version": "1.0",
    "date": "2018-03-23",
    "description": "Release Version"
},
```
I would define a second struct representing a single revision, it should contain  `version` , `date` and `description` members, all of those could be strings, but since we have c++20, I suggest we use [`year_month_day`](https://en.cppreference.com/w/cpp/chrono/year_month_day) for `date`.

2021-03-20 22:39 UTC, ondrys123 commented on include/sparse/common/types.hpp
> +    using data_t = std::unordered_map<std::string, std::string>;
Again, I don't think unordered map is correct approach, because the bibliography is initially ordered, and we want to preserve that ordering. I suggest we use `std::vector` of pairs instead. Or maybe define a struct with named members.

2021-03-20 22:59 UTC, mdugacek commented on include/sparse/common/types.hpp
> +    using data_t = std::unordered_map<std::string, std::string>;
If we need them to be ordered then we can use `std::map`. `nlohmann::json` will then print it with correct braces without any effort on our side.

2021-03-20 23:15 UTC, ondrys123 commented on include/sparse/common/types.hpp
> +    using data_t = std::vector<std::unordered_map<std::string, std::string>>;
correction - we can't use `year_month_day` because this part of chrono only has partial support in both gcc and clang

2021-03-20 23:25 UTC, mdugacek commented
I changed internal type of `other` to `std::map` so we have predictable results.

2021-03-20 23:26 UTC, mdugacek commented
I changed the internal type of `other` to `std::map` so we have predictable output.

2021-03-20 23:28 UTC, mdugacek commented on include/sparse/common/types.hpp
> +    using data_t = std::vector<std::unordered_map<std::string, std::string>>;
I am able to compile it with both `gcc` and `clang`.

2021-03-21 08:58 UTC, ondrys123 commented on include/sparse/common/types.hpp
> +    using data_t = std::unordered_map<std::string, std::string>;
The problem is that with map we lose the ordering, which has to be same as in input file, and there is no guarantee that the bibliography is ordered there, consider `dataset/nscib-cc-0229286sscdkeygen-stv1.2.json`. 
And the numbered bibliography wouldn't be correct either unless the key is number, see https://godbolt.org/z/5M3MbW

2021-03-21 09:31 UTC, misoxxx commented on include/sparse/common/types.hpp
> +    using data_t = std::unordered_map<std::string, std::string>;
I think `map<string,string>` is ok, because in the JSON it is printed as an object and not an array. In JSON, _An object is an unordered set of name/value pairs._, soJSON formatters do not need to preserve any order when printing objects. So I think that both map and unordered_map are ok here.

2021-03-21 09:40 UTC, misoxxx commented on include/sparse/common/types.hpp
> +    using data_t = std::string;
I do not understand the naming convention here. Why do you sometimes declare `data_t` in beginning of struct?

2021-03-21 09:49 UTC, misoxxx commented on include/sparse/common/types.hpp
> +    using data_t = std::string;
I kinda understand the reason why you use it from the pull request text, but I do not understand why it is not consistent and used only sometimes - for example revision does not use it. Second thing strange to me is that `data_t` will mean very different things in different contexts, which might be difficult to read in larger codebase (but is probably ok here as the codebase won't be large).

2021-03-21 11:45 UTC, mdugacek commented on include/sparse/common/types.hpp
> +    using data_t = std::unordered_map<std::string, std::string>;
Actually @ondrys123 is right, we cannot really use `std::map` and just created `json` from it. 
For now, the best solution will probably by to use `std::vector` and do some modifications before printing it to json.

There is one solution that will allow us to use "std::map" (we can create custom `key_type` containing order and text) and specify its comparator and to_json but this solution looks unnecessarily complex for now and we can always change it later.

2021-03-21 12:25 UTC, misoxxx commented on include/sparse/common/types.hpp
> +    using data_t = std::unordered_map<std::string, std::string>;
## Key bibliography
- JSON object with mapping "bibliography tag": "bibliography record"

There is nothing about preserving order, and JSON objects are unordered. So the JSON printer can actually print them in any order. Also, if you look into the code of checker, it does not check order, just whether the correct keys are mapped to correct entries:

`def check_bibliography(actual, expected):
    if not "bibliography" in actual:
        if not "bibliography" in expected:
            return 20
        return 0

    actual = actual["bibliography"]
    expected = expected["bibliography"]

    if len(expected) == 0:
        if len(actual) == 0:
            return 20
        return 0

    max_score = 2 * len(expected)
    score = 0

    for key in actual:
        if key not in expected:
            continue
        score += 1
        score += SequenceMatcher(None, actual[key], expected[key]).ratio()

    return 20 * score / max_score`

2021-03-21 12:36 UTC, ondrys123 commented on include/sparse/common/types.hpp
> +    using data_t = std::unordered_map<std::string, std::string>;
Ok, we can use the map, it will make json stuff easier, I just don't see the reason why we shouldn't preserve the order from the input text file. From the users point of view, would you rather get bibliography in the same way as in the original document (either ordered by numbers or first use), or get something like this
```
[10] : Section 10
[11] : Section 11
[12] : Section 12
[13] : Section 13
[14] : Section 14
[15] : Section 15
[16] : Section 16
[17] : Section 17
[18] : Section 18
[19] : Section 19
[1] : Section 1
[20] : Section 20
[21] : Section 21
[22] : Section 22
[23] : Section 23
[24] : Section 24
[2] : Section 2
[3] : Section 3
[4] : Section 4
[5] : Section 5
[6] : Section 6
[7] : Section 7
[8] : Section 8
[9] : Section 9
```

2021-03-21 12:51 UTC, mdugacek commented on include/sparse/common/types.hpp
> +using bibliography = std::vector<std::string, std::string>;
This is probably does not hold anymore because https://github.com/misoxxx/sparse/pull/13#discussion_r598272797.

2021-03-21 13:04 UTC, mdugacek commented on include/sparse/common/types.hpp
> +    using data_t = std::string;
We are not using this anymore but to answer both questions.
There was consistency. There were two kinds of types, one were holding `parts` of the certificate and these types had `data_t`.

As for the second question. This is quite normal for c++ codebases, even `std` uses this. \
For example `std::vector<int>::value` and ``std::vector<double>::value` are different types.

2021-03-21 13:06 UTC, misoxxx approved these changes

2021-03-21 13:13 UTC, mdugacek commented on include/sparse/common/types.hpp
> +    using data_t = std::unordered_map<std::string, std::string>;
I used `std::unordered_map` because it does not have to be ordered.

2021-03-21 13:48 UTC, ondrys123 approved these changes

2021-03-21 13:53 UTC, merged