Added parsing of bibliography.
misoxxx/sparse pull request #15
Opened 2021-03-23 17:18 UTC by misoxxx

The bibliography is correctly parsed on most testcases.
Also contains tests for the feature.

2021-03-24 01:03 UTC, mdugacek requested changes
Please format the code.

This was just short review to make the code more readable.
I think we should think about a bit of redesign into object because creating always new regexes is really not good from efficiency point of view. It would be best to use them in objects and have them `static`. Or we can use compile [time regexes](https://github.com/hanickadot/compile-time-regular-expressions).

2021-03-24 15:30 UTC, misoxxx commented on src/common/utility.cpp
> +std::string load_file_into_string(const std::string & filename){
I'm not really sure about this function. If the file does not exist, it currently returns empty string - the purpose of this function was easy testing. This could be changed later to throw exception in case the file does not exist.

2021-03-24 22:08 UTC, ondrys123 reviewed
Are the formatting changes in cmake files done by some tool? If so, which? We can all use it and have a uniform formatting across the project. I didn't use and for cmake so far.

2021-03-24 22:08 UTC, ondrys123 commented on tests/common/tests_common.cpp
>  }
```suggestion
```
This was just a placeholder so there's something to compile, it's useless now

2021-03-24 22:08 UTC, ondrys123 commented on src/parsers/parse_bibliography.cpp
> +constexpr int max_length_of_bibliography_entry = 50;
This constant is only used in one function, so it can be defined there. Or we can make common header only for constants, so they are in one place and can be tweaked later more easily. Whichever you choose.

2021-03-25 08:49 UTC, misoxxx commented on cmake/CompileOptions.cmake
> +    "-Wall -Wno-c++98-compat-pedantic -Wno-c++98-compat -Wextra -Wpedantic -Wdouble-promotion -Wnull-dereference -Wimplicit-fallthrough \
Clang warns me about using features of C++ which are not compatible with very old C++ 98. I got few hundreds warnings, so I turned them off, as we do not need compatibility with old standards.

2021-03-25 16:25 UTC, misoxxx commented on src/parsers/parse_bibliography.cpp
> +        possible_bibliography_beginnings.push_back(static_cast<std::size_t>(iter->position(0)));
I added it because I'm getting `warning: implicit conversion changes signedness` here, so I think it's better to have explicit casting.

2021-03-25 21:22 UTC, misoxxx commented on cmake/CompileOptions.cmake
> +    "-Wall -Wno-c++98-compat-pedantic -Wno-c++98-compat -Wextra -Wpedantic -Wdouble-promotion -Wnull-dereference -Wimplicit-fallthrough \
I also added `-EHsc` option, because I could not use exceptions without it on clang-cl.

2021-03-26 12:05 UTC, ondrys123 commented on cmake/CompileOptions.cmake
> +    "-Wall -Wno-c++98-compat-pedantic -Wno-c++98-compat -Wextra -Wpedantic -Wdouble-promotion -Wnull-dereference -Wimplicit-fallthrough \
Ok, I think it's fine and shouldn't cause any problems.

2021-03-26 20:33 UTC, mdugacek commented on src/common/utility.cpp
> +std::string load_file_into_string(const std::string & filename){
Well, you can always remove `nothrow`.

2021-03-27 00:27 UTC, mdugacek commented on cmake/CompileOptions.cmake
> +    "-Wall -Wno-c++98-compat-pedantic -Wno-c++98-compat -Wextra -Wpedantic -Wdouble-promotion -Wnull-dereference -Wimplicit-fallthrough \
I cannot compile the project on both `gcc` and `clang` because of the `-EHsc` as well.

2021-03-27 11:13 UTC, misoxxx commented on cmake/CompileOptions.cmake
> +    "-Wall -Wno-c++98-compat-pedantic -Wno-c++98-compat -Wextra -Wpedantic -Wdouble-promotion -Wnull-dereference -Wimplicit-fallthrough \
I will remove the options and keep them only locally then.

2021-03-27 13:35 UTC, mdugacek commented on cmake/CompileOptions.cmake
> +    "-Wall -Wno-c++98-compat-pedantic -Wno-c++98-compat -Wextra -Wpedantic -Wdouble-promotion -Wnull-dereference -Wimplicit-fallthrough \
After the changes compilig works fine.

2021-03-27 13:57 UTC, mdugacek approved these changes

2021-03-27 15:19 UTC, ondrys123 approved these changes

2021-03-28 10:10 UTC, merged