Parsing table of contents
misoxxx/sparse pull request #19
Opened 2021-04-24 09:22 UTC by misoxxx

2021-04-24 10:13 UTC, mdugacek requested changes

2021-04-24 10:13 UTC, mdugacek commented on src/parsers/parse_toc.cpp
> +        if (split_matches_double_line.size() >= 7 && split_matches_double_line[2].length() > 3)
It would be nice to create named constants from 7 and 3.

2021-04-24 10:13 UTC, mdugacek commented on src/parsers/parse_toc.cpp
> +        else if (split_matches_single_line.size() >= 4 && split_matches_single_line[2].length() > 3)
Again, create named constants from 4 and 3.

2021-04-24 10:13 UTC, mdugacek commented on src/parsers/parse_toc.cpp
> +    common::table_of_contents_t biggest_toc;
If you create this as `std::optional` you do not need the `if` at the end of the function.

2021-04-25 18:08 UTC, ondrys123 requested changes
Looks good, just needs a few tweaks.

2021-04-25 18:08 UTC, ondrys123 commented on src/parsers/parse_toc.cpp
> +    std::sort(table_of_contents.begin(), table_of_contents.end(), &toc_sort);
`toc_sort` is called only once, therefore I think lambda is preferable.
Also, body of this function can be simplified using `std::tie`:
```
return std::tie(lhs.page_number, lhs.id) < std::tie(rhs.page_number, rhs.id);
```

2021-04-25 18:08 UTC, ondrys123 commented on src/parsers/parse_toc.cpp
> +        const auto possible_toc = get_toc(whole_file, i);
`possible_toc` shadows variable declared at line 132, choose a different name

2021-04-26 13:56 UTC, mdugacek approved these changes

2021-04-27 13:27 UTC, ondrys123 approved these changes
Is good

2021-04-27 13:28 UTC, merged