1 basic project structure
misoxxx/sparse pull request #5
Opened 2021-03-18 19:10 UTC by ondrys123

Added basic CMake project, submodules, etc.

2021-03-18 23:24 UTC, mdugacek commented
My CMake is not able to find `CMake`s in `sparse/external/Catch2` and `sparse/external/nlohmann_json`.

Error message:
```
CMake Error at cmake/Dependencies.cmake:3 (add_subdirectory):
  The source directory

    /path/to/sparse/external/Catch2

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:17 (include)


CMake Error at cmake/Dependencies.cmake:6 (add_subdirectory):
  The source directory

    /path/to/sparse/sparse/external/nlohmann_json

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:17 (include)
```

2021-03-18 23:33 UTC, mdugacek commented on modules/parser/main.cpp
> +#include <sparse/common/utility.hpp>
We should probably use `#include "..."` for includes from our project.

2021-03-18 23:33 UTC, mdugacek commented on src/common/utility.cpp
> +#include <sparse/common/utility.hpp>
Again, we should use `"..."`.

2021-03-18 23:33 UTC, mdugacek commented on src/common/utility.cpp
> +#include <nlohmann/json.hpp>
I would also use `#include "..."` for this because `nlohmann` is not installed.

2021-03-18 23:33 UTC, mdugacek commented on tests/common/main.cpp
> +#include <catch2/catch.hpp>
Again, we should use "...".

2021-03-18 23:33 UTC, mdugacek commented on tests/common/tests_common.cpp
> +#include <catch2/catch.hpp>
And again, we should use "...".

2021-03-18 23:34 UTC, mdugacek requested changes
My CMake is not able to find `CMakeLists` in `sparse/external/Catch2` and `sparse/external/nlohmann_json`.

Error message:
```
CMake Error at cmake/Dependencies.cmake:3 (add_subdirectory):
  The source directory

    /path/to/sparse/external/Catch2

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:17 (include)


CMake Error at cmake/Dependencies.cmake:6 (add_subdirectory):
  The source directory

    /path/to/sparse/sparse/external/nlohmann_json

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:17 (include)
```

2021-03-18 23:50 UTC, mdugacek reviewed
It would be nice to add to `README`  that you have to run
```
$ git submodule init
$ git submodule update
```
before running `cmake`.

2021-03-20 18:16 UTC, misoxxx requested changes
V pohode, jedine co mi este chyba je ze ked to skompilujem tak je tam kopa suborov ktore nie su v .gitignore:

        CMakeCache.txt
        CMakeDoxyfile.in
        CMakeDoxygenDefaults.cmake
        CMakeFiles/
        CTestTestfile.cmake
        DartConfiguration.tcl
        Makefile
        _deps/
        cmake_install.cmake
        doc/CMakeFiles/
        doc/CTestTestfile.cmake
        doc/Makefile
        doc/cmake_install.cmake
        doc/html/
        doc/latex/
        modules/CMakeFiles/
        modules/CTestTestfile.cmake
        modules/Makefile
        modules/cmake_install.cmake
        modules/parser/CMakeFiles/
        modules/parser/CTestTestfile.cmake
        modules/parser/Makefile
        modules/parser/cmake_install.cmake
        modules/parser/parser
        src/CMakeFiles/
        src/CTestTestfile.cmake
        src/Makefile
        src/cmake_install.cmake
        src/common/CMakeFiles/
        src/common/CTestTestfile.cmake
        src/common/Makefile
        src/common/cmake_install.cmake
        tests/CMakeFiles/
        tests/CTestTestfile.cmake
        tests/Makefile
        tests/cmake_install.cmake
        tests/common/CMakeFiles/
        tests/common/CTestTestfile.cmake
        tests/common/Makefile
        tests/common/cmake_install.cmake
        tests/common/tests_common

2021-03-20 19:04 UTC, merged